[package]
name = "finclipext"
version = "0.1.0"
edition = "2021"

[lib]
name = "finclipext"
# this is needed to build for iOS and Android.
crate-type = ["staticlib", "lib"]

[features]
testonly = []

[dependencies]
once_cell = "1.10.0"
serde_json = "1.0.81"